### ISSUE TITLE
Brainstorming

### ISSUE THREAD

**Issue by Bruno-Felix** [UnBArqDsw2021-1/2021.1_G6#7]
## Descrição
Issue direcionada para a realizaça e documentação do brainstorming.

## Tarefas
 -  [x] Realizar o brainstorming;
 -  [x] Documentar o artefato.

## Critérios de aceitação
- [x] Brainstoming realizado e devidadmente documentado.

**Comment by DanielPortods** [comment]
![brainstorming](https://user-images.githubusercontent.com/48573556/127262511-4d1468e0-77c5-4580-9c11-5ec3208cfb50.png)
